github:
  organisations:
  - name: activiti
    repositories:
    - name: activiti-examples
      branch: 7.0.x
    - name: activiti-cloud-runtime-bundle-service
      branch: 7.0.x
      useSinglePullRequest: true
    - name: activiti-cloud-service-common
      branch: 7.0.x
      useSinglePullRequest: true
    - name: activiti-cloud-api
      branch: 7.0.x
      useSinglePullRequest: true
    - name: activiti-cloud-org-service
      branch: 7.0.x
      useSinglePullRequest: true
      
